#include "TextureUtils.h"

namespace Portakal
{
	unsigned int TextureUtils::GetFormatSize(const TextureFormat format)
	{
		switch (format)
		{
		case Portakal::TextureFormat::None:
			return 0;;
		case Portakal::TextureFormat::R8_G8_B8_A8_UNorm:
			return 4;
		case Portakal::TextureFormat::B8_G8_R8_A8_UNorm:
			return 4;
		case Portakal::TextureFormat::R8_UNorm:
			return 1;
		case Portakal::TextureFormat::R16_UNorm:
			return 2;
		case Portakal::TextureFormat::R32_G32_B32_A32_Float:
			return 16;
		case Portakal::TextureFormat::R32_Float:
			return 4;
		case Portakal::TextureFormat::BC3_UNorm:
			return 1;
		case Portakal::TextureFormat::D24_UNorm_S8_UInt:
			return 4;
		case Portakal::TextureFormat::D32_Float_S8_UInt:
			return 5;
		case Portakal::TextureFormat::R32_G32_B32_A32_UInt:
			return 16;
		case Portakal::TextureFormat::R8_G8_SNorm:
			return 2;
		case Portakal::TextureFormat::BC1_Rgb_UNorm:
			return 3;
		case Portakal::TextureFormat::BC1_Rgba_UNorm:
			return 4;
		case Portakal::TextureFormat::BC2_UNorm:
			return 2;
		case Portakal::TextureFormat::R10_G10_B10_A2_UNorm:
			return 4;
		case Portakal::TextureFormat::R10_G10_B10_A2_UInt:
			return 4;
		case Portakal::TextureFormat::R11_G11_B10_Float:
			return 4;
		case Portakal::TextureFormat::R8_SNorm:
			return 1;
		case Portakal::TextureFormat::R8_UInt:
			return 1;
		case Portakal::TextureFormat::R8_SInt:
			return 1;
		case Portakal::TextureFormat::R16_SNorm:
			return 2;
		case Portakal::TextureFormat::R16_UInt:
			return 2;
		case Portakal::TextureFormat::R16_SInt:
			return 2;
		case Portakal::TextureFormat::R16_Float:
			return 2;
		case Portakal::TextureFormat::R32_UInt:
			return 4;
		case Portakal::TextureFormat::R32_SInt:
			return 4;
		case Portakal::TextureFormat::R8_G8_UNorm:
			return 2;
		case Portakal::TextureFormat::R8_G8_UInt:
			return 2;
		case Portakal::TextureFormat::R8_G8_SInt:
			return 2;
		case Portakal::TextureFormat::R16_G16_UNorm:
			return 4;
		case Portakal::TextureFormat::R16_G16_SNorm:
			return 4;
		case Portakal::TextureFormat::R16_G16_UInt:
			return 4;
		case Portakal::TextureFormat::R16_G16_SInt:
			return 4;
		case Portakal::TextureFormat::R16_G16_Float:
			return 4;
		case Portakal::TextureFormat::R32_G32_UInt:
			return 8;
		case Portakal::TextureFormat::R32_G32_SInt:
			return 8;
		case Portakal::TextureFormat::R32_G32_Float:
			return 8;
		case Portakal::TextureFormat::R8_G8_B8_A8_SNorm:
			return 4;
		case Portakal::TextureFormat::R8_G8_B8_A8_UInt:
			return 4;
		case Portakal::TextureFormat::R8_G8_B8_A8_SInt:
			return 4;
		case Portakal::TextureFormat::R16_G16_B16_A16_UNorm:
			return 8;
		case Portakal::TextureFormat::R16_G16_B16_A16_SNorm:
			return 8;
		case Portakal::TextureFormat::R16_G16_B16_A16_UInt:
			return 8;
		case Portakal::TextureFormat::R16_G16_B16_A16_SInt:
			return 8;
		case Portakal::TextureFormat::R16_G16_B16_A16_Float:
			return 8;
		case Portakal::TextureFormat::R32_G32_B32_A32_SInt:
			return 16;
		case Portakal::TextureFormat::ETC2_R8_G8_B8_UNorm:
			return 4;
		case Portakal::TextureFormat::ETC2_R8_G8_B8_A1_UNorm:
			return 4;
		case Portakal::TextureFormat::ETC2_R8_G8_B8_A8_UNorm:
			return 4;
		case Portakal::TextureFormat::BC4_UNorm:
			return 0;
		case Portakal::TextureFormat::BC4_SNorm:
			return 0;
		case Portakal::TextureFormat::BC5_UNorm:
			return 0;
		case Portakal::TextureFormat::BC5_SNorm:
			return 0;
		case Portakal::TextureFormat::BC7_UNorm:
			return 0;
		case Portakal::TextureFormat::R8_G8_B8_A8_UNorm_SRgb:
			return 4;
		case Portakal::TextureFormat::B8_G8_R8_A8_UNorm_SRgb:
			return 4;
		case Portakal::TextureFormat::BC1_Rgb_UNorm_SRgb:
			return 3;
		case Portakal::TextureFormat::BC1_Rgba_UNorm_SRgb:
			return 4;
		case Portakal::TextureFormat::BC2_UNorm_SRgb:
			return 3;
		case Portakal::TextureFormat::BC3_UNorm_SRgb:
			return 3;
		case Portakal::TextureFormat::BC7_UNorm_SRgb:
			return 3;
		default:
			return 0;
			break;
		}
	}
}