#pragma once

#ifdef PORTAKAL_OS_WINDOWS
#include <Runtime/Win32/Win32API.h>
#else
#endif

//MISC
#define PORTAKAL_API PORTAKAL_API_IMPL


//FILE
#define PLATFORM_FOLDER_NAME_SIZE PLATFORM_FOLDER_NAME_SIZE_IMPL
#define PLATFORM_FILE_NAME_SIZE PLATFORM_FILE_NAME_SIZE_IMPL