#include "ResourceSubObject.h" 
START_GENERATE_TYPE(ResourceSubObject);
START_CLASS_TYPE_PROPERTIES(ResourceSubObject)
REGISTER_BASE_TYPE(TaggedObject);

END_TYPE_PROPERTIES;
NO_DEFAULT_CONSTRUCTOR;
END_GENERATE_TYPE(ResourceSubObject);