#include "DefaultComponentVisualizer.h" 
START_GENERATE_TYPE(DefaultComponentVisualizer);
START_CLASS_TYPE_PROPERTIES(DefaultComponentVisualizer)
REGISTER_BASE_TYPE(EditorComponentVisualizer);

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(DefaultComponentVisualizer);
END_GENERATE_TYPE(DefaultComponentVisualizer);