#include "SpriteCameraComponentVisualizer.h" 
START_GENERATE_TYPE(SpriteCameraComponentVisualizer);
START_CLASS_TYPE_PROPERTIES(SpriteCameraComponentVisualizer)
REGISTER_BASE_TYPE(EditorComponentVisualizer);
REGISTER_TYPE_ATTRIBUTE(CustomEditorComponentAttribute, typeof(SpriteCameraComponent))
END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(SpriteCameraComponentVisualizer);
END_GENERATE_TYPE(SpriteCameraComponentVisualizer);