#include "EditorObjectVisualizer.h" 
START_GENERATE_TYPE(EditorObjectVisualizer);
START_CLASS_TYPE_PROPERTIES(EditorObjectVisualizer)

END_TYPE_PROPERTIES;
NO_DEFAULT_CONSTRUCTOR;
END_GENERATE_TYPE(EditorObjectVisualizer);