#include "InputModule.h" 
START_GENERATE_TYPE(InputModule);
START_TYPE_PROPERTIES(InputModule)
REGISTER_BASE_TYPE(ApplicationModule);

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(InputModule);
END_GENERATE_TYPE(InputModule);