#include "GUICustomMenuItem.h" 
START_GENERATE_TYPE(GUICustomMenuItem);
START_TYPE_PROPERTIES(GUICustomMenuItem)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(GUICustomMenuItem);
END_GENERATE_TYPE(GUICustomMenuItem);
