#include "GUIMenuItemBehaviour.h" 
START_GENERATE_TYPE(GUIMenuItemBehaviour);
START_CLASS_TYPE_PROPERTIES(GUIMenuItemBehaviour)

END_TYPE_PROPERTIES;
NO_DEFAULT_CONSTRUCTOR;
END_GENERATE_TYPE(GUIMenuItemBehaviour);