#include "SceneComponentFieldEntry.h" 
START_GENERATE_TYPE(SceneComponentFieldEntry);
START_STRUCT_TYPE_PROPERTIES(SceneComponentFieldEntry)
REGISTER_FIELD(SceneComponentFieldEntry,FieldName,String,AccessSpecifier::Public);
REGISTER_FIELD(SceneComponentFieldEntry,Type,SceneComponentFieldType,AccessSpecifier::Public);
REGISTER_FIELD(SceneComponentFieldEntry,Content,String,AccessSpecifier::Public);

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(SceneComponentFieldEntry);
END_GENERATE_TYPE(SceneComponentFieldEntry);