#include "ProjectModule.h" 
START_GENERATE_TYPE(ProjectModule);
START_CLASS_TYPE_PROPERTIES(ProjectModule)
REGISTER_BASE_TYPE(ApplicationModule);

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(ProjectModule);
END_GENERATE_TYPE(ProjectModule);