#include "TestWindow.h" 
START_GENERATE_TYPE(TestWindow);
START_TYPE_PROPERTIES(TestWindow)
REGISTER_BASE_TYPE(EditorWindow);

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(TestWindow);
END_GENERATE_TYPE(TestWindow);
