#include "EditorComponentVisualizer.h" 
START_GENERATE_TYPE(EditorComponentVisualizer);
START_TYPE_PROPERTIES(EditorComponentVisualizer)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(EditorComponentVisualizer);
END_GENERATE_TYPE(EditorComponentVisualizer);