#include "EditorComponentVisualizer.h" 
START_GENERATE_TYPE(EditorComponentVisualizer);
START_CLASS_TYPE_PROPERTIES(EditorComponentVisualizer)

END_TYPE_PROPERTIES;
NO_DEFAULT_CONSTRUCTOR;
END_GENERATE_TYPE(EditorComponentVisualizer);