#include "YamlSerializerAttribute.h" 
START_GENERATE_TYPE(YamlSerializerAttribute);
START_CLASS_TYPE_PROPERTIES(YamlSerializerAttribute)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(YamlSerializerAttribute);
END_GENERATE_TYPE(YamlSerializerAttribute);