#include "TestEnum.h"
START_GENERATE_ENUM(TestEnum);
REGISTER_ENUM(A,0);
REGISTER_ENUM(B,1);
REGISTER_ENUM(C,2);
REGISTER_ENUM(D,3);
REGISTER_ENUM(E,4);
REGISTER_ENUM(F,5);
REGISTER_ENUM(G,6);

END_GENERATE_ENUM(TestEnum);