#include "CustomAssetOpenOperationAttribute.h" 
START_GENERATE_TYPE(CustomAssetOpenOperationAttribute);
START_TYPE_PROPERTIES(CustomAssetOpenOperationAttribute)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(CustomAssetOpenOperationAttribute);
END_GENERATE_TYPE(CustomAssetOpenOperationAttribute);