#include "CustomAssetImporterAttribute.h" 
START_GENERATE_TYPE(CustomAssetImporterAttribute);
START_TYPE_PROPERTIES(CustomAssetImporterAttribute)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(CustomAssetImporterAttribute);
END_GENERATE_TYPE(CustomAssetImporterAttribute);
