#include "CustomAssetAuthoringToolAttribute.h" 
START_GENERATE_TYPE(CustomAssetAuthoringToolAttribute);
START_CLASS_TYPE_PROPERTIES(CustomAssetAuthoringToolAttribute)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(CustomAssetAuthoringToolAttribute);
END_GENERATE_TYPE(CustomAssetAuthoringToolAttribute);