#include "CustomAssetSerializerAttribute.h" 
START_GENERATE_TYPE(CustomAssetSerializerAttribute);
START_TYPE_PROPERTIES(CustomAssetSerializerAttribute)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(CustomAssetSerializerAttribute);
END_GENERATE_TYPE(CustomAssetSerializerAttribute);
