#include "CustomAssetProcessorAttribute.h" 
START_GENERATE_TYPE(CustomAssetProcessorAttribute);
START_TYPE_PROPERTIES(CustomAssetProcessorAttribute)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(CustomAssetProcessorAttribute);
END_GENERATE_TYPE(CustomAssetProcessorAttribute);