#include "CustomAssetVisualizerAttribute.h" 
START_GENERATE_TYPE(CustomAssetVisualizerAttribute);
START_CLASS_TYPE_PROPERTIES(CustomAssetVisualizerAttribute)

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(CustomAssetVisualizerAttribute);
END_GENERATE_TYPE(CustomAssetVisualizerAttribute);