#include "IAssetOpenOperation.h" 
START_GENERATE_TYPE(IAssetOpenOperation);
START_TYPE_PROPERTIES(IAssetOpenOperation)

END_TYPE_PROPERTIES;
NO_DEFAULT_CONSTRUCTOR;
END_GENERATE_TYPE(IAssetOpenOperation);