#include "GUIWindowModule.h" 
START_GENERATE_TYPE(GUIWindowModule);
START_CLASS_TYPE_PROPERTIES(GUIWindowModule)
REGISTER_BASE_TYPE(ApplicationModule);

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(GUIWindowModule);
END_GENERATE_TYPE(GUIWindowModule);