#include "GraphicsModule.h" 
START_GENERATE_TYPE(GraphicsModule);
START_CLASS_TYPE_PROPERTIES(GraphicsModule)
REGISTER_BASE_TYPE(ApplicationModule);

END_TYPE_PROPERTIES;
NO_DEFAULT_CONSTRUCTOR;
END_GENERATE_TYPE(GraphicsModule);