#include "Scene.h" 
START_GENERATE_TYPE(Scene);
START_CLASS_TYPE_PROPERTIES(Scene)
REGISTER_BASE_TYPE(ResourceSubObject);

END_TYPE_PROPERTIES;
HAS_DEFAULT_CONSTRUCTOR(Scene);
END_GENERATE_TYPE(Scene);