#include "RenderTarget.h" 
START_GENERATE_TYPE(RenderTarget);
START_CLASS_TYPE_PROPERTIES(RenderTarget)
REGISTER_BASE_TYPE(ResourceSubObject);

END_TYPE_PROPERTIES;
NO_DEFAULT_CONSTRUCTOR;
END_GENERATE_TYPE(RenderTarget);